export enum TypeDropBoxFileEnum {
  //image
  jpg = 'jpg',
  jpeg = 'jpeg',
  jfif = 'jfif',
  pjpeg = 'pjpeg',
  pjp = 'pjp',
  png = 'png',
  svg = 'svg',
  webp = 'webp',
  avif = 'avif',
  JPG = 'JPG',
  JPEG = 'JPEG',
  JFIF = 'JFIF',
  PJPEG = 'PJPEG',
  PJP = 'PJP',
  PNG = 'PNG',
  SVG = 'SVG',
  WEBP = 'WEBP',
  AVIF = 'AVIF',
  //video
  mp4 = 'mp4',
  mov = 'mov',
  wmv = 'wmv',
  avchd = 'avchd',
  flv = 'flv',
  f4v = 'f4v',
  swf = 'swf',
  mkv = 'mkv',
  webm = 'webm',
  avi = 'avi',
  MP4 = ' MP4  ',
  MOV = ' MOV  ',
  WMV = 'WMV  ',
  AVCHD = ' AVCHD',
  FLV = ' FLV  ',
  F4V = ' F4V  ',
  SWF = ' SWF  ',
  MKV = ' MKV  ',
  WEBM = ' WEBM ',
  AVI = '  AVI',
  rar = 'rar',
  zip = 'zip',
   pdf= 'pdf',
  octet_stream='octet-stream'
}
